name: Build and deploy Next.js app to Azure Web App - bhavani-bojedla

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload full app folder
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write         # ✅ Required for Azure OIDC login
      contents: read          # ✅ Required for checking out repo, etc.
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3559113D4F3646929919D0CDFDBE2553 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FA065BAB3DF4DE1BF57D3D243A3E4AD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C7B80B0A5A6243DD9B81956C65DE73E6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bhavani-bojedla'
          slot-name: 'Production'
          package: .
